### ISSUE TITLE
Establish contributor agreement in workflow

### ISSUE THREAD

**Issue by twindus** [NWChemEx-Project/DeveloperTools#113]
We'd like to automate having contributors sign the contributor agreement. Ideally a new contributor would be presented with a pop-up (or something) that provides a link to our contributor agreement and a box saying they accept or don't accept it. They'd have to accept it if they want to contribute.

A quick search suggests that https://cla-assistant.io/ looks promising.

The CLA text:
```
By contributing computer software code to the NWChemEx project I certify that the contribution 
is being made under the Apache 2.0 license (https://www.apache.org/licenses/LICENSE-2.0) and
that I have all rights and permissions necessary to do so, including authorization from my
employer if applicable.

NOTICE. This Software was developed under funding from the U.S. Department of Energy and the 
U.S. Government consequently retains certain rights. As such, the U.S. Government has been 
granted for itself and others acting on its behalf a paid-up, nonexclusive, irrevocable, 
worldwide license in the Software to reproduce, distribute copies to the public, prepare 
derivative works, and perform publicly and display publicly, and to permit others to do so.
```

**Comment by ryanmrichard** [comment]
@twindus do you have the literal words of the contributor agreement? Assuming it's short enough maybe just edit the original post so that it contains it?

**Comment by twindus** [comment]
Here is what the final information is from David Long (PNNL IP Legal Affairs):

"It appears that we have agreement among the Parties that all contributions to NWChemEx will be under the Apache 2.0 open source license, and that this can be done simply by reference to that license. The following will be included on the site:
 
By contributing computer software code to the NWChemEx project I certify that the contribution is being made under the 
Apache 2.0 license ([https://www.apache.org/licenses/LICENSE-2.0](https://www.apache.org/licenses/LICENSE-2.0)) and that I have all rights and permissions necessary to do so, including authorization from my employer if applicable.
 
And contributions can include reference to that license (rather than the full text):
 
Copyright 202X CONTRIBUTING ENTITY.
Contributed under the Apache 2.0 license (https://www.apache.org/licenses/LICENSE-2.0)
 
As appropriate the contribution can also include a disclaimer:
 
NOTICE. This Software was developed under funding from the U.S. Department of Energy and the U.S. Government consequently retains certain rights. As such, the U.S. Government has been granted for itself and others acting on its behalf a paid-up, nonexclusive, irrevocable, worldwide license in the Software to reproduce, distribute copies to the public, prepare derivative works, and perform publicly and display publicly, and to permit others to do so."

I hope that clarifies it?

**Comment by ryanmrichard** [comment]
@twindus actually it does not. What is the literal text of the CLA? What you pasted seems to have intermittent comments. Is the CLA itself just:

```
By contributing computer software code to the NWChemEx project I certify that the contribution is being made under the
Apache 2.0 license (https://www.apache.org/licenses/LICENSE-2.0) and that I have all rights and permissions necessary to do so, including authorization from my employer if applicable.
```

or is it:

```
By contributing computer software code to the NWChemEx project I certify that the contribution is being made under the
Apache 2.0 license (https://www.apache.org/licenses/LICENSE-2.0) and that I have all rights and permissions necessary to do so, including authorization from my employer if applicable.

NOTICE. This Software was developed under funding from the U.S. Department of Energy and the U.S. Government consequently retains certain rights. As such, the U.S. Government has been granted for itself and others acting on its behalf a paid-up, nonexclusive, irrevocable, worldwide license in the Software to reproduce, distribute copies to the public, prepare derivative works, and perform publicly and display publicly, and to permit others to do so.
```

The copyright stuff is part of the licensing (and will be handled by #116). I'm not sure where the "NOTICE" should go (probably part of the CLA since contributors have to agree to it, but maybe also on the README).

**Comment by twindus** [comment]
@ryanmrichard The second one is the one that I would go with.  It could probably go into the README as well.

**Comment by ryanmrichard** [comment]
@twindus Thanks! That clears it up. I updated the OP to reflect this.

**Comment by ryanmrichard** [comment]
This should be taken care of. I set it up so that members of the organization do not have to sign the CLA, but outside contributors do. I think CLA only applies to public repos; so I suspect most people won't see its effects for a while.
