### ISSUE TITLE
Merge this Repo with .github?

### ISSUE THREAD

**Issue by ryanmrichard** [NWChemEx-Project/DeveloperTools#126]
As I understand it the .github repo is basically meant to manage an organization's GitHub presence. For the most part, that's what DeveloperTools was also doing. FWIW DeveloperTools was created before the .github repos were thing (or at the very least before I knew they were a thing).

Thoughts?

**Comment by ryanmrichard** [comment]
Should have clarified when I assigned you, I was thinking more of you taking point on putting this to a vote as opposed to actually doing it. 

The main things in this repo (that need to moved) are the documentation and the CMake scripts. `.github/workflows`, `ci/lint`, and `scripts` can be deleted (The former is already moved, the two latter are no longer used).

**Comment by twindus** [comment]
I've send it to the slack channel to discuss.

**Comment by twindus** [comment]
Closed since it is a replica of the one in .github.  The issues are also going to be moved, so that should more or less close out the merge.
