### ISSUE TITLE
Hunter Stuff

### ISSUE THREAD

**Issue by ryanmrichard** [NWChemEx-Project/DeveloperTools#33]
The purpose of this issue is to keep track of various pain points and gotchas that arise as we finish transitioning to Hunter.  So far everything on the list is something that we can work around by wrapper functions, but if the list gets too large we want to consider other options. The list so far:

- No automatic forwarding of CMake settings to dependencies
  - We expected Hunter to propagate these settings, but Hunter actually wants you to use a toolchain file for dependencies
     - See [here](https://docs.hunter.sh/en/latest/overview/customization/toolchain-id.html) for more details
- Requirement that repos have SHA1 hashes
  - For dependencies tracking master, need to update hash every time master changes
  - Admittedly problem goes away when the repo has stable releases (could in theory track a commit)
- Package repository is a central GitHub repo owned and maintained largely by the Hunter team
  - While a great idea for mature dependencies, it has notable shortcomings for private repos and repos in development
  - The ability to add additional channels would go a long way
     - Came across [this](https://github.com/ruslo/hunter/issues/640) discussion on Hunter
- Arguably simply a minor annoyance, the Hunter cache is hard to clean-up without just wiping it.
  - Failed builds and  bad options lead to bunches of copies of libraries (protected by hashes of those bad options, meaning they won't be used) that just take up space

**Comment by ajaypanyala** [comment]
`No automatic forwarding of CMake settings to dependencies`
- You mentioned a config file in NWChemEx-Project/Utilities#31 used to control the dependency settings. Would the following approach work cleanly: generate a config file containing the user specified CMake settings (along with other options) for dependencies (OR) simply generate the toolchain file.

**Comment by ryanmrichard** [comment]
@ajaypanyala I'm not a big fan of generating files.  A cleaner solution is to wrap the call within the `config` file.  Inside the wrapper you concatenate the CMake args the user provides with the usual ones (*e.g.*, `CMAKE_CXX_COMPILER`, `CMAKE_C_COMPILER`, `CMAKE_CXX_FLAGS`).  This will require some tweaking so as not to clash with Hunter, which must be using some of the variables (like `CMAKE_INSTALL_PREFIX` to control where the dependencies get installed).

**Comment by ajaypanyala** [comment]
I was not sure if the user provided CMake args are visible inside the `config` file. If they are, then of course this is the way to go.

**Comment by ryanmrichard** [comment]
With CPP starting to roll out to NWX repos Hunter isn't an issue any more.
