### ISSUE TITLE
Create our own actions for CI reusability

### ISSUE THREAD

**Issue by ryanmrichard** [NWChemEx-Project/DeveloperTools#91]
Huge thanks to @AutonomicPerfectionist for creating [this](https://github.com/CMakePP/cminx-auto-update-action) action for CMinx. Using that action as a template, it shouldn't be too hard to create actions for NWX's CI which replace the Bash scripts we've been synchronizing with the `files-sync-action`.

**Comment by twindus** [comment]
@ryanmrichard Assuming this is still an issue unless you say otherwise.

**Comment by ryanmrichard** [comment]
I think we can close this. This issue was more a way to reduce copy/pasting CI infrastructure than anything else. We accomplished that with the reusable workflows.
